### ISSUE TITLE
conf files generated

### ISSUE THREAD

**Issue by NGE2015** [gabatronic/hestia-netcore#1]
I created a subdomain and changed the Proxy Template to netcore500 or socket option.
both give the same error : Error: nginx restart failed

nginx: [emerg] unexpected “{” in /etc/nginx/conf.d/domains/..com.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

I grab the generated conf that is located at /etc/nginx/conf.d/domains
and it seem that for this config it was loaded all the “payload” and >not< only the

server {
listen [example.com](http://example.com/);
…

Another thing:
How do you start the Blazor server app ?

**Comment by mguinness** [comment]
Did you resolve your issues?  I see you created a [fork](https://github.com/NGE2015/hestia-netcore) with changes.  I was able to get my application running and I've created a PR to update the documentation and a minor bug.

**Comment by NGE2015** [comment]
I was able to fix it , but I also did a modification .
Create a script file where it generate a service and something else to be able to execute that bash and ask for the service name I want and .dll name to be executed 

This for the socket version.

**Comment by mguinness** [comment]
For others to reference, mods are in https://github.com/NGE2015/hestia-netcore/blob/main/netcoresock.sh and show how to setup app in `systemd`.
